# Generated by Django 4.2.3 on 2023-08-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access_records',
            old_name='athor',
            new_name='author',
        ),
    ]
