# Generated by Django 4.2.3 on 2023-08-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_athor_access_records_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_records',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
